---
apiVersion: v1
kind: Namespace
metadata:
  name: api

---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: api-gw
  namespace: api
  labels:
    app: api
    name: api-gw
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - "*.192.168.39.155.nip.io"
    tls:
      httpsRedirect: false
