---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gateway-ingress-es
  namespace: playground
spec:
  eventBusName: jetstream-eb
  template:
    serviceAccountName: playground-sa
  resource:
    ingress:
      namespace: playground
      group: ""
      version: v1
      resource: services
      eventTypes: [ ADD, DELETE, UPDATE ]
      filter:
        fields:
        - key: metadata.annotations.autodeploy-ingress-host
          operation: =
          value: ".+"

    gateway:
      namespace: playground
      group: ""
      version: v1
      resource: services
      eventTypes: [ ADD, DELETE, UPDATE ]
      filter:
        fields:
        - key: metadata.annotations.autodeploy-gateway-host
          operation: =
          value: ".+"
