---
apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
  namespace: argo-rollouts
type: Opaque
stringData:
  slack-token: my-slack-token
  url-endpoint: http://notification.ops.svc.cluster.local
  url-token: my-url-token
