---
apiVersion: v1
kind: Namespace
metadata:
  name: playground

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: playground
data:
  # root
  MINIO_ROOT_USER: cm9vdA==
  # rootroot
  MINIO_ROOT_PASSWORD: cm9vdHJvb3Q=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: playground
data:
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...2}.minio-hsvc.playground.svc.cluster.local/data
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"

---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: playground
  labels:
    app: minio
    labels: minio-hsvc
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
    - name: minio-data 
      port: 9000
      targetPort: 9000
    - name: minio-web 
      port: 9090
      targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: playground
  labels:
    app: minio
    name: minio-sts
spec:
  replicas: 3
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: [ ReadWriteOncePod ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      containers:
      - name: minio-container
        image: bitnami/minio:2024
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: minio-secret
        - configMapRef:
            name: minio-cm
        ports:
        - name: data-port
          containerPort: 9000
        - name: web-port
          containerPort: 9090
        volumeMounts:
        - name: data-vol
          mountPath: /data

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: playground
  labels:
    app: minio-svc
spec:
  selector:
    app: minio
    name: minio-po
  type: ClusterIP
  ports:
  - name: data-port
    port: 9000
    targetPort: 9000
  - name: web-port
    port: 9090
    targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: playground
  labels:
    app: minio
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
  - host: data-192.168.39.241.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
  - host: web-192.168.39.241.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9090
