---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: Tunnel
metadata:
  name: cf-tunnel
  namespace: playground 
spec:
  newTunnel:
    name: cf-tunnel
  size: 1
  cloudflare:
    email: __EMAIL__
    domain: __DOMAIN__
    secret: cloudflare-secrets
    accountId: __CF_ACCOUNT_ID__
  image: cloudflare/cloudflared:2024.5.0

---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: github-es-tb
  namespace: playground
  labels:
    app: github
    name: github-es-tb

tunnelRef:
  kind: Tunnel
  name: cf-tunnel
subjects:
- kind: Service
  name: github-es-svc
  spec:
    target: http://github-es-svc.playground.svc.cluster.local:13000
    # webhook domain name configured in Github
    fqdn: __GITHUB_WEBHOOK__
    protocol: https
