---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: Tunnel
metadata:
  name: cf-tunnel
  namespace: playground 
spec:
  newTunnel:
    name: cf-tunnel
  size: 1
  cloudflare:
    email: __EMAIL__
    domain: __DOMAIN__
    secret: cloudflare-secrets
    accountId: __CF_ACCOUNT_ID__

---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: github-es-tb
  namespace: playground
  labels:
    app: github
    name: github-es-tb

tunnelRef:
  kind: Tunnel
  name: cf-tunnel
subjects:
- kind: Service
  # domain name will be github.your_domain.com
  name: github
  spec:
    target: http://github-es-svc.playground.svc.cluster.local:13000
