---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-ro
  namespace: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
      name: api-po
  strategy:
    canary:
      stableService: api-svc
      canaryService: canary-api-svc
      maxSurge: 25%
      maxUnavailable: 1
      steps:
      - setCanaryScale:
          weight: 25
      - setWeight: 1
      - setHeaderRoute:
          name: canary
          match:
          - headerName: X-Version
            headerValue:
              exact: 'v2'
      - pause: { duration: 30s }
      - analysis:
          templates:
          - templateName: availability-analysis
          args:
          - name: url 
            value: "http://api-192.168.39.200.nip.io/api/data"
          - name: canaryHeader
            value: "X-Version"
          - name: canaryValue
            value: "v2"
          - name: duration
            value: 6m
      - analysis:
          templates:
          - templateName: request-latency-analysis
          args:
          - name: jobName 
            value: api
          - name: serviceName
            value: "canary-api-svc"
          - name: latency
            value: "5"

      trafficRouting:
        managedRoutes:
        - name: canary
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: api-httproute
            useHeaderRoutes: true
            namespace: api
  template:
    metadata:
      labels:
        app: api
        name: api-po
    spec:
      containers:
      - name: api-container
        image: chukmunnlee/fake-api:v1-otel
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            port: 3000
            path: /healthz
        ports:
        - name: api-port
          containerPort: 3000
        - name: metrics
          containerPort: 9464
