---
apiVersion: v1
kind: Namespace
metadata:
  name: api

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: api
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
    name: api-po
  ports:
  - name: api-port
    port: 3000
    targetPort: 3000
  - name: metrics
    port: 9464
    targetPort: 9464

---
apiVersion: v1
kind: Service
metadata:
  name: canary-api-svc
  namespace: api
  labels:
    app: api
    scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: api
    name: api-po
  ports:
  - name: api-port
    port: 3000
    targetPort: 3000
  - name: metrics
    port: 9464
    targetPort: 9464

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-httproute
  namespace: api
  labels:
    app: api
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: web
  hostnames:
  - api-192.168.39.200.nip.io
  rules:
    - matches:
      - path:
          value: /api
          type: PathPrefix
      backendRefs:
      - name: api-svc
        port: 3000
      - name: canary-api-svc
        port: 3000

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: api-smon
  namespace: api
  labels:
    release: prometheus
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: api
      scrape: "true"
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
