---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: web-analysis
  namespace: api
spec:
  args:
  - name: url
  - name: header
  - name: value
  metrics:
  - name: success
    successCondition: result == "{{ args.value }}"
    provider:
      web:
        url: "{{ args.url }}"
        headers:
        - key: "{{ args.header }}"
          value: " {{ args.value }}"
        jsonPath: "{$.version}"
        timeoutSeconds: 5

